// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: decimal/fee/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines calculation constants for the module.
// Naming convention: <module_name><transaction_as_verb><something_additional>
// Parameters measurement is units (10^15)
type Params struct {
	// 1 byte fee
	// commission part by transaction size
	ByteFee uint64 `protobuf:"varint,1,opt,name=byteFee,proto3" json:"byte_fee" yaml:"byte_fee"`
	// coin transactions fees
	CoinSend              uint64 `protobuf:"varint,2,opt,name=coinSend,proto3" json:"coin_send" yaml:"coin_send"`
	CoinSendMultiAddition uint64 `protobuf:"varint,3,opt,name=coinSendMultiAddition,proto3" json:"coin_send_multi_addition" yaml:"coin_send_multi_addition"`
	CoinBuy               uint64 `protobuf:"varint,4,opt,name=coinBuy,proto3" json:"coin_buy" yaml:"coin_buy"`
	CoinSell              uint64 `protobuf:"varint,5,opt,name=coinSell,proto3" json:"coin_sell" yaml:"coin_sell"`
	// common transaction commission
	CoinCreate uint64 `protobuf:"varint,6,opt,name=coinCreate,proto3" json:"coin_create" yaml:"coin_create"`
	// special commission depends on coin symbol length
	CoinCreateLength3     uint64 `protobuf:"varint,7,opt,name=coinCreateLength3,proto3" json:"coin_create_length_3" yaml:"coin_create_length_3"`
	CoinCreateLength4     uint64 `protobuf:"varint,8,opt,name=coinCreateLength4,proto3" json:"coin_create_length_4" yaml:"coin_create_length_4"`
	CoinCreateLength5     uint64 `protobuf:"varint,9,opt,name=coinCreateLength5,proto3" json:"coin_create_length_5" yaml:"coin_create_length_5"`
	CoinCreateLength6     uint64 `protobuf:"varint,10,opt,name=coinCreateLength6,proto3" json:"coin_create_length_6" yaml:"coin_create_length_6"`
	CoinCreateLengthOther uint64 `protobuf:"varint,11,opt,name=coinCreateLengthOther,proto3" json:"coin_create_length_other" yaml:"coin_create_length_other"`
	// multisignature wallets
	MultisigCreateWallet      uint64 `protobuf:"varint,12,opt,name=multisigCreateWallet,proto3" json:"multisig_create_wallet" yaml:"multisig_create_wallet"`
	MultisigCreateTransaction uint64 `protobuf:"varint,13,opt,name=multisigCreateTransaction,proto3" json:"multisig_create_transaction" yaml:"multisig_create_transaction"`
	MultisigSignTransaction   uint64 `protobuf:"varint,14,opt,name=multisigSignTransaction,proto3" json:"multisig_sign_transaction" yaml:"multisig_sign_transaction"`
	// validator operations
	ValidatorDeclareCandidate uint64 `protobuf:"varint,15,opt,name=validatorDeclareCandidate,proto3" json:"validator_declare_candidate" yaml:"validator_declare_candidate"`
	ValidatorEditCandidate    uint64 `protobuf:"varint,16,opt,name=validatorEditCandidate,proto3" json:"validator_edit_candidate" yaml:"validator_edit_candidate"`
	ValidatorDelegate         uint64 `protobuf:"varint,17,opt,name=validatorDelegate,proto3" json:"validator_delegate" yaml:"validator_delegate"`
	ValidatorUnbond           uint64 `protobuf:"varint,18,opt,name=validatorUnbond,proto3" json:"validator_unbond" yaml:"validator_unbond"`
	ValidatorSetOnline        uint64 `protobuf:"varint,19,opt,name=validatorSetOnline,proto3" json:"validator_set_online" yaml:"validator_set_online"`
	ValidatorSetOffline       uint64 `protobuf:"varint,20,opt,name=validatorSetOffline,proto3" json:"validator_set_offline" yaml:"validator_set_offline"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d019b262529661a, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "decimal.fee.v1.Params")
}

func init() { proto.RegisterFile("decimal/fee/v1/params.proto", fileDescriptor_4d019b262529661a) }

var fileDescriptor_4d019b262529661a = []byte{
	// 796 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x96, 0x4b, 0x6f, 0xfb, 0x44,
	0x14, 0xc5, 0x13, 0xf8, 0xd3, 0xc7, 0xb4, 0x34, 0xed, 0x34, 0x6d, 0xa7, 0x14, 0x32, 0x65, 0x24,
	0x24, 0x36, 0x8d, 0x55, 0xe5, 0x81, 0x5a, 0x84, 0x50, 0x5b, 0xca, 0x8a, 0xaa, 0xc8, 0x05, 0x21,
	0xd8, 0x58, 0x93, 0x78, 0xe2, 0x5a, 0x9d, 0xd8, 0x95, 0x3d, 0x69, 0x89, 0x58, 0xb2, 0x61, 0xc9,
	0x92, 0x65, 0x3f, 0x0e, 0xcb, 0x2e, 0x59, 0x8d, 0x50, 0xba, 0x41, 0x5e, 0xfa, 0x13, 0x20, 0x8f,
	0xe3, 0x47, 0x1c, 0x27, 0x3b, 0xe7, 0x9e, 0x73, 0xcf, 0xef, 0x5e, 0x6b, 0x62, 0x0d, 0x38, 0x32,
	0x59, 0xdf, 0x1e, 0x52, 0xae, 0x0d, 0x18, 0xd3, 0x9e, 0x4e, 0xb5, 0x47, 0xea, 0xd1, 0xa1, 0xdf,
	0x7c, 0xf4, 0x5c, 0xe1, 0xc2, 0xad, 0xa9, 0xd8, 0x1c, 0x30, 0xd6, 0x7c, 0x3a, 0xfd, 0xa8, 0x6e,
	0xb9, 0x96, 0xab, 0x24, 0x2d, 0x7a, 0x8a, 0x5d, 0x64, 0x52, 0x03, 0x2b, 0xdf, 0xab, 0x36, 0x78,
	0x06, 0x56, 0x7b, 0x63, 0xc1, 0xbe, 0x65, 0x0c, 0x55, 0x8f, 0xab, 0x9f, 0xbf, 0xbb, 0xc4, 0x81,
	0xc4, 0x6b, 0x51, 0xc9, 0x18, 0x30, 0x16, 0x4a, 0x5c, 0x1b, 0xd3, 0x21, 0x3f, 0x27, 0x49, 0x85,
	0xe8, 0x89, 0x1f, 0x7e, 0x05, 0xd6, 0xfa, 0xae, 0xed, 0xdc, 0x31, 0xc7, 0x44, 0xef, 0xa9, 0xde,
	0x4f, 0x03, 0x89, 0xd7, 0xa3, 0x9a, 0xe1, 0x33, 0xc7, 0x0c, 0x25, 0xde, 0x8e, 0x9b, 0xd3, 0x12,
	0xd1, 0xd3, 0x16, 0x38, 0x02, 0x7b, 0xc9, 0xf3, 0xcd, 0x88, 0x0b, 0xfb, 0xc2, 0x34, 0x6d, 0x61,
	0xbb, 0x0e, 0x7a, 0x5f, 0x65, 0x7d, 0x1d, 0x48, 0x8c, 0xd2, 0x46, 0x63, 0x18, 0x59, 0x0c, 0x3a,
	0xf5, 0x84, 0x12, 0xe3, 0x42, 0x74, 0xc1, 0x41, 0xf4, 0xf2, 0xf4, 0x68, 0xe1, 0x48, 0xb8, 0x1c,
	0x8d, 0xd1, 0xbb, 0x6c, 0x61, 0x15, 0xd3, 0x1b, 0x8d, 0xb3, 0x85, 0x93, 0x0a, 0xd1, 0x13, 0x7f,
	0xb6, 0x30, 0xe7, 0xe8, 0x83, 0xb9, 0x85, 0x39, 0x9f, 0x5b, 0x98, 0xf3, 0x74, 0x61, 0xce, 0xe1,
	0x35, 0x00, 0xd1, 0xf3, 0x95, 0xc7, 0xa8, 0x60, 0x68, 0x45, 0x05, 0x7c, 0x16, 0x48, 0xbc, 0xa1,
	0xdc, 0x7d, 0x55, 0x0e, 0x25, 0x86, 0xb9, 0x88, 0xb8, 0x48, 0xf4, 0x5c, 0x23, 0x64, 0x60, 0x27,
	0xfb, 0xf5, 0x1d, 0x73, 0x2c, 0x71, 0xdf, 0x42, 0xab, 0x2a, 0xed, 0x8b, 0x40, 0xe2, 0x7a, 0xae,
	0xd1, 0xe0, 0x4a, 0x36, 0x5a, 0xa1, 0xc4, 0x47, 0x73, 0xb1, 0xa9, 0x4a, 0xf4, 0xf9, 0xc4, 0x32,
	0x4c, 0x1b, 0xad, 0x2d, 0xc5, 0xb4, 0x97, 0x62, 0xda, 0x25, 0x98, 0x76, 0x19, 0xa6, 0x83, 0xd6,
	0x97, 0x62, 0x3a, 0x4b, 0x31, 0x9d, 0x12, 0x4c, 0xa7, 0x0c, 0xd3, 0x45, 0x60, 0x29, 0xa6, 0xbb,
	0x14, 0xd3, 0x2d, 0xc1, 0x74, 0x93, 0x33, 0x9d, 0x2f, 0xde, 0x8a, 0x7b, 0xe6, 0xa1, 0x8d, 0xc2,
	0x99, 0x9e, 0x0d, 0x73, 0x23, 0x4f, 0xe1, 0x4c, 0x97, 0x38, 0xa6, 0x67, 0x7a, 0x2e, 0x1d, 0xba,
	0xa0, 0xae, 0x4e, 0xbf, 0x6f, 0x5b, 0xb1, 0xf8, 0x13, 0xe5, 0x9c, 0x09, 0xb4, 0xa9, 0xa8, 0x5f,
	0x06, 0x12, 0xef, 0x27, 0x7a, 0x92, 0xfb, 0xac, 0x1c, 0xa1, 0xc4, 0x9f, 0xc4, 0xcc, 0x72, 0x9d,
	0xe8, 0xa5, 0xc1, 0xf0, 0xf7, 0x2a, 0x38, 0x9c, 0x15, 0x7e, 0xf0, 0xa8, 0xe3, 0xd3, 0xbe, 0xfa,
	0x03, 0x7f, 0xa8, 0xb0, 0xd7, 0x81, 0xc4, 0x47, 0xc5, 0x58, 0x91, 0xd9, 0x42, 0x89, 0x49, 0x39,
	0x3b, 0x67, 0x22, 0xfa, 0x62, 0x0e, 0xfc, 0x0d, 0x1c, 0x24, 0xe2, 0x9d, 0x6d, 0x39, 0xf9, 0x11,
	0xb6, 0xd4, 0x08, 0x17, 0x81, 0xc4, 0x69, 0xbf, 0xe1, 0xdb, 0x96, 0x53, 0x18, 0xe0, 0xb8, 0x30,
	0x40, 0xd1, 0x42, 0xf4, 0x45, 0x04, 0xf5, 0x0a, 0x9e, 0x28, 0xb7, 0x4d, 0x2a, 0x5c, 0xef, 0x1b,
	0xd6, 0xe7, 0xd4, 0x63, 0x57, 0xd4, 0x31, 0xa3, 0x02, 0x43, 0xb5, 0xec, 0x15, 0xa4, 0x26, 0xc3,
	0x8c, 0x5d, 0x46, 0x3f, 0xb1, 0x65, 0xaf, 0x60, 0x89, 0x89, 0xe8, 0x8b, 0x39, 0xf0, 0x19, 0xec,
	0xa7, 0xe2, 0xb5, 0x69, 0x8b, 0x6c, 0x82, 0xed, 0xec, 0xc4, 0x65, 0xe1, 0xcc, 0xb4, 0xc5, 0x0c,
	0x1e, 0x17, 0xf1, 0xb3, 0x0e, 0xa2, 0x2f, 0x88, 0x87, 0x14, 0xec, 0xe4, 0xa6, 0xe2, 0xcc, 0x8a,
	0x98, 0x3b, 0x8a, 0xd9, 0x0a, 0x24, 0x86, 0xf9, 0x85, 0x62, 0x35, 0x94, 0xf8, 0x70, 0x7e, 0xd9,
	0x58, 0x23, 0xfa, 0x7c, 0x1a, 0xfc, 0x19, 0xd4, 0xd2, 0xe2, 0x8f, 0x4e, 0xcf, 0x75, 0x4c, 0x04,
	0x15, 0x40, 0x0b, 0x24, 0xde, 0xce, 0x42, 0x46, 0x4a, 0x0b, 0x25, 0x3e, 0x28, 0xc6, 0xc7, 0x0a,
	0xd1, 0x8b, 0x39, 0xd0, 0x02, 0xd9, 0x80, 0x77, 0x4c, 0xdc, 0x3a, 0xdc, 0x76, 0x18, 0xda, 0xcd,
	0xbe, 0x07, 0x59, 0x86, 0xcf, 0x84, 0xe1, 0x2a, 0x3d, 0xfb, 0x1e, 0x94, 0xa9, 0x44, 0x2f, 0x89,
	0x84, 0x0f, 0x60, 0x77, 0xa6, 0x3a, 0x18, 0x28, 0x52, 0x5d, 0x91, 0xce, 0x02, 0x89, 0xf7, 0x0a,
	0x59, 0xb1, 0x21, 0x94, 0xf8, 0xe3, 0x52, 0x54, 0x2c, 0x13, 0xbd, 0x2c, 0xf5, 0x7c, 0xf3, 0x8f,
	0x17, 0x5c, 0xf9, 0xeb, 0x05, 0x57, 0xfe, 0x7b, 0xc1, 0xd5, 0xcb, 0x9b, 0xbf, 0x27, 0x8d, 0xea,
	0xeb, 0xa4, 0x51, 0xfd, 0x77, 0xd2, 0xa8, 0xfe, 0xf9, 0xd6, 0xa8, 0xbc, 0xbe, 0x35, 0x2a, 0xff,
	0xbc, 0x35, 0x2a, 0xbf, 0xb4, 0x7a, 0xb6, 0xe8, 0x8d, 0xfa, 0x0f, 0x4c, 0x34, 0x5d, 0xcf, 0xd2,
	0xa6, 0x57, 0x06, 0xc1, 0xe8, 0x50, 0xb3, 0xdc, 0x13, 0x7f, 0x48, 0x3d, 0x71, 0xe2, 0xb8, 0x26,
	0xd3, 0x7e, 0x55, 0x77, 0x0c, 0x31, 0x7e, 0x64, 0x7e, 0x6f, 0x45, 0x5d, 0x1d, 0x5a, 0xff, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x22, 0x73, 0xd9, 0xb3, 0x7f, 0x08, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ByteFee != that1.ByteFee {
		return false
	}
	if this.CoinSend != that1.CoinSend {
		return false
	}
	if this.CoinSendMultiAddition != that1.CoinSendMultiAddition {
		return false
	}
	if this.CoinBuy != that1.CoinBuy {
		return false
	}
	if this.CoinSell != that1.CoinSell {
		return false
	}
	if this.CoinCreate != that1.CoinCreate {
		return false
	}
	if this.CoinCreateLength3 != that1.CoinCreateLength3 {
		return false
	}
	if this.CoinCreateLength4 != that1.CoinCreateLength4 {
		return false
	}
	if this.CoinCreateLength5 != that1.CoinCreateLength5 {
		return false
	}
	if this.CoinCreateLength6 != that1.CoinCreateLength6 {
		return false
	}
	if this.CoinCreateLengthOther != that1.CoinCreateLengthOther {
		return false
	}
	if this.MultisigCreateWallet != that1.MultisigCreateWallet {
		return false
	}
	if this.MultisigCreateTransaction != that1.MultisigCreateTransaction {
		return false
	}
	if this.MultisigSignTransaction != that1.MultisigSignTransaction {
		return false
	}
	if this.ValidatorDeclareCandidate != that1.ValidatorDeclareCandidate {
		return false
	}
	if this.ValidatorEditCandidate != that1.ValidatorEditCandidate {
		return false
	}
	if this.ValidatorDelegate != that1.ValidatorDelegate {
		return false
	}
	if this.ValidatorUnbond != that1.ValidatorUnbond {
		return false
	}
	if this.ValidatorSetOnline != that1.ValidatorSetOnline {
		return false
	}
	if this.ValidatorSetOffline != that1.ValidatorSetOffline {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidatorSetOffline != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ValidatorSetOffline))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.ValidatorSetOnline != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ValidatorSetOnline))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.ValidatorUnbond != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ValidatorUnbond))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.ValidatorDelegate != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ValidatorDelegate))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.ValidatorEditCandidate != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ValidatorEditCandidate))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.ValidatorDeclareCandidate != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ValidatorDeclareCandidate))
		i--
		dAtA[i] = 0x78
	}
	if m.MultisigSignTransaction != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MultisigSignTransaction))
		i--
		dAtA[i] = 0x70
	}
	if m.MultisigCreateTransaction != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MultisigCreateTransaction))
		i--
		dAtA[i] = 0x68
	}
	if m.MultisigCreateWallet != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MultisigCreateWallet))
		i--
		dAtA[i] = 0x60
	}
	if m.CoinCreateLengthOther != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CoinCreateLengthOther))
		i--
		dAtA[i] = 0x58
	}
	if m.CoinCreateLength6 != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CoinCreateLength6))
		i--
		dAtA[i] = 0x50
	}
	if m.CoinCreateLength5 != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CoinCreateLength5))
		i--
		dAtA[i] = 0x48
	}
	if m.CoinCreateLength4 != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CoinCreateLength4))
		i--
		dAtA[i] = 0x40
	}
	if m.CoinCreateLength3 != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CoinCreateLength3))
		i--
		dAtA[i] = 0x38
	}
	if m.CoinCreate != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CoinCreate))
		i--
		dAtA[i] = 0x30
	}
	if m.CoinSell != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CoinSell))
		i--
		dAtA[i] = 0x28
	}
	if m.CoinBuy != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CoinBuy))
		i--
		dAtA[i] = 0x20
	}
	if m.CoinSendMultiAddition != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CoinSendMultiAddition))
		i--
		dAtA[i] = 0x18
	}
	if m.CoinSend != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CoinSend))
		i--
		dAtA[i] = 0x10
	}
	if m.ByteFee != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ByteFee))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ByteFee != 0 {
		n += 1 + sovParams(uint64(m.ByteFee))
	}
	if m.CoinSend != 0 {
		n += 1 + sovParams(uint64(m.CoinSend))
	}
	if m.CoinSendMultiAddition != 0 {
		n += 1 + sovParams(uint64(m.CoinSendMultiAddition))
	}
	if m.CoinBuy != 0 {
		n += 1 + sovParams(uint64(m.CoinBuy))
	}
	if m.CoinSell != 0 {
		n += 1 + sovParams(uint64(m.CoinSell))
	}
	if m.CoinCreate != 0 {
		n += 1 + sovParams(uint64(m.CoinCreate))
	}
	if m.CoinCreateLength3 != 0 {
		n += 1 + sovParams(uint64(m.CoinCreateLength3))
	}
	if m.CoinCreateLength4 != 0 {
		n += 1 + sovParams(uint64(m.CoinCreateLength4))
	}
	if m.CoinCreateLength5 != 0 {
		n += 1 + sovParams(uint64(m.CoinCreateLength5))
	}
	if m.CoinCreateLength6 != 0 {
		n += 1 + sovParams(uint64(m.CoinCreateLength6))
	}
	if m.CoinCreateLengthOther != 0 {
		n += 1 + sovParams(uint64(m.CoinCreateLengthOther))
	}
	if m.MultisigCreateWallet != 0 {
		n += 1 + sovParams(uint64(m.MultisigCreateWallet))
	}
	if m.MultisigCreateTransaction != 0 {
		n += 1 + sovParams(uint64(m.MultisigCreateTransaction))
	}
	if m.MultisigSignTransaction != 0 {
		n += 1 + sovParams(uint64(m.MultisigSignTransaction))
	}
	if m.ValidatorDeclareCandidate != 0 {
		n += 1 + sovParams(uint64(m.ValidatorDeclareCandidate))
	}
	if m.ValidatorEditCandidate != 0 {
		n += 2 + sovParams(uint64(m.ValidatorEditCandidate))
	}
	if m.ValidatorDelegate != 0 {
		n += 2 + sovParams(uint64(m.ValidatorDelegate))
	}
	if m.ValidatorUnbond != 0 {
		n += 2 + sovParams(uint64(m.ValidatorUnbond))
	}
	if m.ValidatorSetOnline != 0 {
		n += 2 + sovParams(uint64(m.ValidatorSetOnline))
	}
	if m.ValidatorSetOffline != 0 {
		n += 2 + sovParams(uint64(m.ValidatorSetOffline))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ByteFee", wireType)
			}
			m.ByteFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ByteFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinSend", wireType)
			}
			m.CoinSend = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinSend |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinSendMultiAddition", wireType)
			}
			m.CoinSendMultiAddition = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinSendMultiAddition |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinBuy", wireType)
			}
			m.CoinBuy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinBuy |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinSell", wireType)
			}
			m.CoinSell = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinSell |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinCreate", wireType)
			}
			m.CoinCreate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinCreate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinCreateLength3", wireType)
			}
			m.CoinCreateLength3 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinCreateLength3 |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinCreateLength4", wireType)
			}
			m.CoinCreateLength4 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinCreateLength4 |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinCreateLength5", wireType)
			}
			m.CoinCreateLength5 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinCreateLength5 |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinCreateLength6", wireType)
			}
			m.CoinCreateLength6 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinCreateLength6 |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinCreateLengthOther", wireType)
			}
			m.CoinCreateLengthOther = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinCreateLengthOther |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultisigCreateWallet", wireType)
			}
			m.MultisigCreateWallet = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MultisigCreateWallet |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultisigCreateTransaction", wireType)
			}
			m.MultisigCreateTransaction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MultisigCreateTransaction |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultisigSignTransaction", wireType)
			}
			m.MultisigSignTransaction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MultisigSignTransaction |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorDeclareCandidate", wireType)
			}
			m.ValidatorDeclareCandidate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorDeclareCandidate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorEditCandidate", wireType)
			}
			m.ValidatorEditCandidate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorEditCandidate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorDelegate", wireType)
			}
			m.ValidatorDelegate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorDelegate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorUnbond", wireType)
			}
			m.ValidatorUnbond = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorUnbond |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSetOnline", wireType)
			}
			m.ValidatorSetOnline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorSetOnline |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSetOffline", wireType)
			}
			m.ValidatorSetOffline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorSetOffline |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
